version: "3"
services:
  app:
    build: .
    image: docker.waramity-dating
    env_file: .env
    restart: unless-stopped
    tty: true
    ports:
      - "56730:80"
    volumes:
      # - ./:/var/www
      - ./:/app
    networks:
      - frontend
      - backend
    command: gunicorn --worker-class eventlet -w 4 -b :56730 wsgi:app
    # command: uwsgi --http :56730 --gevent 1000 --http-websockets --master --wsgi-file wsgi.py --callable app

  nginx:
    # build:
    #   context: nginx
    #   dockerfile: Dockerfile
    image: nginx:alpine
    container_name: ngnix
    restart: unless-stopped
    tty: true
    ports:
      - "56728:80"
      # - "80:80"
      # - "443:443"
    volumes:
      # - nginx:/etc/nginx
      # - app:/var/www
      # - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

    depends_on:
      - app
    networks:
      - frontend

#Docker Networks
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

#Volumes
volumes:
  app:
    driver: local
  nginx:
    driver: local
